FROM centos:6

RUN yum -y install \
    gcc \
    make \
    kernel-devel \
    iptables-devel \
    net-snmp \
    net-snmp-devel \
    which

CMD ./configure --kdir=$(echo /usr/src/kernels/*) && make all

